name: toolforge

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  AWS_ACCOUNT_ID: ${{ vars.TOOLFORGE_AWS_ACCOUNT_ID }}
  GITHUB_ORGANIZATION: ${{ vars.ORGANIZATION }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3.10.0
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Configure Maven
        env:
          MAVEN_SETTINGS: ${{ secrets.MAVEN_SETTINGS }}
        run: mkdir -p ~/.m2 && echo "$MAVEN_SETTINGS" >~/.m2/settings.xml
      - name: Cache local Maven repository
        uses: actions/cache@v3.3.1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Login to ToolForge Docker
        uses: toolforgeio-actions/toolforge-docker-login@v1
        with:
          api-key: ${{ secrets.TOOLFORGE_API_KEY }}
      - name: Configure AWS credentials for us-east-1
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-oidc-${{ env.GITHUB_ORGANIZATION }}-role
          aws-region: us-east-1
      - name: Login to Amazon ECR Public Registry
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      - name: Build and Deploy to ToolForge
        run: mvn -B clean compile install docker:push